export const RECEIVE_LOGIN_STATE = "RECEIVE_LOGIN_STATE";
export const START_LOGIN = "START_LOGIN";
export const RECEIVE_TOKEN = "RECEIVE_TOKEN";
export const FAILED_LOGIN = "FAILED_LOGIN";
export const LOGOUT = "LOGOUT";
