export const START_FETCH_GAME_PARTICIPANTS = "START_FETCH_GAME_PARTICIPANTS";
export const RECEIVE_GAME_PARTICIPANTS = "RECEIVE_GAME_PARTICIPANTS";
export const RECEIVE_GAME_PARTICIPANT = "RECEIVE_GAME_PARTICIPANT";
